spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ResourceApplication
          uri: lb://ResourceApplication
#          uri: localhost:8080/
          predicates:
#            - Path=/**
            - Path=/ResourceApplication/**
          filters:
            - StripPrefix=1
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://app-e:8761/eureka
#      defaultZone: http://localhost:8761/eureka