version: '3.5'
services:
  apps:
    container_name: appSong
    image: app-song
    build:
      context: .
    ports:
      - "8090:8090"
    expose:
      - 8090
    networks:
      - my-proxy-net
      - internalS
    depends_on:
      - dbs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbs:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  dbs:
    image: postgres
    ports:
      - "54321:5432"
    networks:
      - internalS
    expose:
      - 54321
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
networks:
  my-proxy-net:
    name: custom_network
    external: true
  internalS:
    name: internalS

